apiVersion: v1
kind: Secret
metadata:
  name: {{ include "three-tier-app.fullname" . }}-db
type: Opaque
stringData:
  DB_PASSWORD: {{ required "backend.env.dbPassword must be set" .Values.backend.env.dbPassword | quote }}
